/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IssueTracker;

import ConnectionToDatabase.Cnx;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ChangeLogForm extends javax.swing.JFrame {
    private int projectID;
    /**
     * Creates new form ChangeLogForm
     */
    public ChangeLogForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public ChangeLogForm(int projectID){
        this.projectID = projectID;
        initComponents();
        this.setLocationRelativeTo(null);
        insertTableContents();
    }
    private void insertTableContents(){
         ArrayList<ChangeLog> list = createList(); // object referring to the ArrayList created inside createList();
        DefaultTableModel tableModel = (DefaultTableModel)changeLogTable.getModel(); // get the model of table GUI
        Object[] row = new Object[3];
        for(int i = 0; i<list.size(); i++){  
            row[0] = list.get(i).getUserName(); 
            row[1] = list.get(i).getDate();
            row[2] = list.get(i).getDescription();
            tableModel.addRow(row); //inserting data into specific row of table GUI
        }
    }
    
    private ArrayList<ChangeLog> createList(){
            ArrayList<ChangeLog> list = new ArrayList<>();
        try {
            Cnx connectionClass = new Cnx(); //establish connection
            Connection connection = connectionClass.getConnection(); //establish connection
            
            String userName;
            String date;
            String description;
            String query1 = "SELECT* FROM changelog where projectID = " + projectID + " order by date"; //query to select all from table named 'changeLog'
            Statement st = connection.createStatement(); //create a statement using connection that already establish
            
            ResultSet result1 = st.executeQuery(query1); // execute query1 and store the result into result1
            
            while(result1.next()){
                userName = result1.getString("userName");
                date = result1.getTimestamp("date").toString();
                description = result1.getString("description");
                list.add(new ChangeLog(projectID,userName,date,description)); // instantiate ChangeLog object and insert it into ArrayList
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ChangeLogForm.class.getName()).log(Level.SEVERE, null, ex); // will just print the errors to our console
        }
        return list; //return the ArrayList
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        changeLogLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        changeLogTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        changeLogLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        changeLogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeLogLabel.setText("Change Log");

        changeLogTable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        changeLogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Time", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(changeLogTable);
        if (changeLogTable.getColumnModel().getColumnCount() > 0) {
            changeLogTable.getColumnModel().getColumn(0).setMinWidth(120);
            changeLogTable.getColumnModel().getColumn(0).setPreferredWidth(120);
            changeLogTable.getColumnModel().getColumn(0).setMaxWidth(120);
            changeLogTable.getColumnModel().getColumn(1).setMinWidth(160);
            changeLogTable.getColumnModel().getColumn(1).setPreferredWidth(160);
            changeLogTable.getColumnModel().getColumn(1).setMaxWidth(160);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(changeLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(changeLogLabel)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeLogForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeLogLabel;
    private javax.swing.JTable changeLogTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
